# Personal preferences
Metrics/LineLength:
  Max: 99
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/TrailingWhitespace:
  Enabled: false
Style/RedundantReturn:
  Enabled: false

# inherit_from: .rubocop_todo.yml
