# Personal preferences
Metrics/MethodLength:
  Max: 12
Metrics/LineLength:
  Max: 92
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/TrailingWhitespace:
  Enabled: false
Style/RedundantReturn:
  Enabled: false

# inherit_from: .rubocop_todo.yml
